# Platform.sh configuration for Laravel
name: edusphere
type: php:8.2

build:
    flavor: composer
    dependencies:
        php:
            - "php8.2-redis"
            - "php8.2-gd"
            - "php8.2-mysql"
            - "php8.2-xml"
            - "php8.2-mbstring"
            - "php8.2-zip"
            - "php8.2-curl"
            - "php8.2-bcmath"
    commands:
        build: |
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

web:
    commands:
        start: "php-fpm"
    upstream:
        socket_family: unix
        socket: "unix://tmp/app.sock"
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            expires: 1h
            allow: true

disk: 2048

mounts:
    "storage":
        source: local
        source_path: storage

relationships:
    database: "mysql:mysql"
    redis: "redis:redis"

variables:
    env:
        APP_ENV: production
        APP_DEBUG: false
        LOG_LEVEL: error

